version: "3"
services:
  nginx:
    container_name: korakot-cms-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - korakot-cms
    volumes:
      - ./server.crt:/etc/ssl/certs/server.crt
      - ./server.key:/etc/ssl/private/server.key
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public/uploads:/opt/app/public/uploads
      # - ./certbot/www:/var/www/certbot/:ro
      # - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - korakot-cms

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --force-renewal -d ${CERTBOT_DOMAIN}
  #   networks:
  #     - korakot-cms

  korakot-cms:
    container_name: korakot-cms
    build: .
    image: korakot-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
    depends_on:
      - meilisearch
    links:
      - meilisearch
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - korakot-cms

  meilisearch:
    image: getmeili/meilisearch:latest
    volumes:
      - ./meili_data:/meili_data
    ports:
      - "7700"
    networks:
      - korakot-cms
    environment:
      - MEILI_MASTER_KEY=-Hmt61V9p-tyo3B9r5oIynItL_9JzTVSg5jgpFFwskY

volumes:
  korakot-cms-data:
networks:
  korakot-cms:
    name: korakot-cms
    driver: bridge
