/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import restCache from "@strapi-community/plugin-rest-cache/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "rest-cache": restCache,
    "users-permissions": usersPermissions,
    meilisearch: meilisearch,
  },
});
